### PR TITLE
Populated setting fragment

### PR DESCRIPTION
**Pull request by peterTorres7**
Added user settings. 

Screen Shot 2021-06-06 at 6 28 53 PM

### CODE REVIEW

**Review by ChristopherNavo — DISMISSED** [review]
Tried it out.  Looks great, Peter

**Review by Theillusionofthegift — CHANGES_REQUESTED** [review]
just need to fix the merge errors

**Review by mfern08 — APPROVED** [review]
Looks good!

**Review by ChristopherNavo — APPROVED** [review]
Conflicts resolved *updated* approval -CN

**Pull request merged**
