### PR TITLE
A simple visual representation of the Vendor Profile

### PR DESCRIPTION
**Pull request by TimnLyt**
Let me know if I'm setting up this merge correctly. This is just a simple representation of what the Vendor Profile page will look like visually. I'll try to add more and make it look better as things move, as well as more functionality.

### CODE REVIEW

**Comment by TimnLyt** [comment]
Some of the changes might have been from me updating stuff and most likely forgetting that I was on our group's project and not on my own project. Sorry about that.

**Review by mfern08 — APPROVED** [review]
Looks good Tim! I like the design approach of the profile :)

**Review by ChristopherNavo — APPROVED** [review]
Looking good to me too Tim.  Great visual! Thanks for fleshing the Vendor Profile fragment out.

**Review by peterTorres7 — APPROVED** [review]
Looks good Tim! Good job!

**Pull request merged**
