### PR TITLE
Food description

### PR DESCRIPTION
**Pull request by peterTorres7**
A basic layout for food description.

### CODE REVIEW

**Review by TimnLyt — DISMISSED** [review]
Looks good Peter! Great job!

**Review by ChristopherNavo — DISMISSED** [review]
Nice!  Looks Great to me Peter.

**Review by TimnLyt — APPROVED** [review]
I think we have to approve it again because it says there were new changes made since last review. I think you just need one more to merge.

**Review by ChristopherNavo — APPROVED** [review]
Looks great Peter!

**Pull request merged**
